"""
app.py — Siemens Energy NL-to-SQL Demo
Streamlit UI for Pipeline 2 (Energy Domain)

Run: streamlit run app.py
"""

import json
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from query_agent_v2 import run_query

# ── Page config ────────────────────────────────────────────────────
st.set_page_config(
    page_title="Siemens Energy — NL-to-SQL",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Load ontology for sidebar ──────────────────────────────────────
@st.cache_resource
def load_ontology_cached():
    with open("ontology.json") as f:
        return json.load(f)

ontology = load_ontology_cached()

# ── Sidebar ────────────────────────────────────────────────────────
with st.sidebar:
    st.image("semantic_graph_v2.png", use_container_width=True)
    st.divider()

    st.markdown("### 🏭 Entities")
    for node in ontology["nodes"]:
        domain_icon = "🔵" if node["schema"] == "domain1" else "🟢"
        st.markdown(f"{domain_icon} **{node['label']}** `{node['table']}`")
        st.caption(node["description"])

    st.divider()
    st.markdown("### 🔗 Relationships")
    for edge in ontology["edges"]:
        cross = "🔀" if edge["cross_db"] else "→"
        st.markdown(
            f"`{edge['from_label']}` {cross} **{edge['relationship']}** `{edge['to_label']}`"
        )

    st.divider()
    st.markdown("### 💡 Try these queries")
    example_queries = [
        "What is the breakdown of assets by equipment class?",
        "Which assets have the most critical outages?",
        "Show all P1 emergency cases and which assets they belong to",
        "Which campaigns have the highest budget?",
        "Which engineers own the most active campaigns?",
        "What product families are most involved in delayed maintenance events?",
        "Which asset equipment classes appear most in critical severity outages and have open service cases?",
    ]
    for q in example_queries:
        if st.button(q, key=q, use_container_width=True):
            st.session_state["query_input"] = q
            st.session_state["run_query"] = True


# ── Main ───────────────────────────────────────────────────────────
st.title("⚡ Siemens Energy — NL-to-SQL")
st.caption(
    "Ask questions in plain English across two databases — "
    "relationships auto-inferred, SQL generated by Claude Haiku"
)

# Query input
col1, col2 = st.columns([5, 1])
with col1:
    query_input = st.text_input(
        "Ask a question",
        value=st.session_state.get("query_input", ""),
        placeholder="e.g. Which assets have the most critical outages?",
        label_visibility="collapsed",
    )
with col2:
    run_btn = st.button("Run ▶", type="primary", use_container_width=True)

# Trigger from sidebar button or Run button
should_run = run_btn or st.session_state.pop("run_query", False)

if should_run and query_input.strip():
    with st.spinner("Generating SQL and running query..."):
        result = run_query(query_input.strip())

    # ── Error ──────────────────────────────────────────────────────
    if result["error"]:
        st.error(result["error"])

    else:
        # ── Explanation + SQL ──────────────────────────────────────
        st.success(f"💬 {result['explanation']}")

        with st.expander("🔍 View generated SQL", expanded=False):
            st.code(result["sql"], language="sql")

        # ── Results + chart side by side ───────────────────────────
        df = result["data"]
        chart = result["chart"]

        if not df.empty:
            if chart["type"] != "none" and chart.get("x") and chart.get("y"):
                col_data, col_chart = st.columns([1, 1])
            else:
                col_data = st.container()
                col_chart = None

            with col_data:
                st.markdown(f"**Results** — {len(df):,} rows")
                st.dataframe(df, use_container_width=True, height=400)

            if col_chart and chart["type"] != "none":
                with col_chart:
                    st.markdown(f"**{chart.get('title', 'Chart')}**")
                    x_col = chart.get("x")
                    y_col = chart.get("y")

                    if x_col in df.columns and y_col in df.columns:
                        plot_df = df[[x_col, y_col]].dropna()

                        fig, ax = plt.subplots(figsize=(7, 4))
                        fig.patch.set_facecolor("#0E1117")
                        ax.set_facecolor("#0E1117")

                        if chart["type"] == "bar":
                            ax.bar(
                                plot_df[x_col].astype(str),
                                plot_df[y_col],
                                color="#1A6EBF",
                                edgecolor="#0E1117",
                            )
                            ax.set_xlabel(x_col, color="white", fontsize=9)
                            ax.set_ylabel(y_col, color="white", fontsize=9)
                            plt.xticks(
                                rotation=35, ha="right", color="white", fontsize=8
                            )

                        elif chart["type"] == "line":
                            ax.plot(
                                plot_df[x_col].astype(str),
                                plot_df[y_col],
                                color="#1A6EBF",
                                marker="o",
                                linewidth=2,
                            )
                            ax.set_xlabel(x_col, color="white", fontsize=9)
                            ax.set_ylabel(y_col, color="white", fontsize=9)
                            plt.xticks(
                                rotation=35, ha="right", color="white", fontsize=8
                            )

                        elif chart["type"] == "scatter":
                            ax.scatter(
                                plot_df[x_col],
                                plot_df[y_col],
                                color="#1A6EBF",
                                alpha=0.7,
                                edgecolors="white",
                                linewidths=0.4,
                            )
                            ax.set_xlabel(x_col, color="white", fontsize=9)
                            ax.set_ylabel(y_col, color="white", fontsize=9)

                        ax.tick_params(colors="white")
                        for spine in ax.spines.values():
                            spine.set_edgecolor("#333333")
                        ax.yaxis.label.set_color("white")
                        plt.tight_layout()
                        st.pyplot(fig, use_container_width=True)
                        plt.close()
        else:
            st.info("Query returned no results.")

elif should_run and not query_input.strip():
    st.warning("Please enter a question.")

# ── Graph tab at the bottom ────────────────────────────────────────
st.divider()
tab1, tab2 = st.tabs(["🧠 Semantic Graph", "🔧 Structural Graph"])

with tab1:
    st.image("semantic_graph_v2.png", caption="LLM-inferred semantic ontology — entities and named relationships", use_container_width=True)

with tab2:
    try:
        st.image("schema_graph.png", caption="Structural schema graph — FK column names and DB boundaries", use_container_width=True)
    except Exception:
        st.info("schema_graph.png not found — run schema_graph.py from Pipeline 1 to generate it.")
